FROM  ubuntu:latest

WORKDIR  /app

COPY requirements.txt /app
COPY project /app/project

RUN apt-get update && apt-get install -y python3-pip

RUN pip3 install --no-cache-dir -r requirements.txt
EXPOSE  8000

ENTRYPOINT [ "python3" ]
CMD ["manage.py", "runserver", "0.0.0.0:8000"]



